region                                               = "ap-south-1"
vpc_name                                             = "nimbuspost-dev-vpc"
cidr_block                                           = "10.52.0.0/16"
igw_name                                             = "nimbuspost-dev-igw"
pub_rt_name                                          = "nimbuspost-dev-pub"
nat_name                                             = "nimbuspost-dev-nat"
pvt_rt_name                                          = "nimbuspost-dev-pvt"
enable_igw_publicRouteTable_PublicSubnets_resource   = true
enable_public_web_security_group_resource            = false
enable_pub_alb_resource                              = false
enable_aws_route53_zone_resource                     = false
pub_subnet_name                                      = "nimbuspost-dev-pub-sub"
DB_pvt_subnet_name                                   = "nimbuspost-dev-db-sub"
DB_private_subnets_cidr                              = ["10.52.12.0/23", "10.52.14.0/23"]
Middleware_pvt_subnet_name                           = "nimbuspost-dev-mw-sub"
Middleware_private_subnets_cidr                      = ["10.52.18.0/23", "10.52.20.0/23"]
public_subnets_cidr                                  = ["10.52.1.0/24", "10.52.2.0/24"]
App_pvt_subnet_name                                  = "nimbuspost-dev-app-sub"
App_private_subnets_cidr                             = ["10.52.24.0/21", "10.52.32.0/21"]
avaialability_zones                                  = ["ap-south-1a", "ap-south-1b"]
